name: Daily, Push, and Manual Triggered Update
on:
  schedule:
    - cron: '0 12 * * *'  # Runs every day at 12:00 PM (UTC)
  push:
    branches:
      - main  # Triggers the workflow on every push to the 'main' branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Geckodriver
      uses: browser-actions/setup-geckodriver@latest
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        geckodriver-version: 'latest'

    - name: Run daily update script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python llm_poll_parser/daily_update.py

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add .
        if git diff-index --quiet HEAD; then
          echo "No changes to commit"
        else
          git commit -m "Daily update: $(date +'%Y-%m-%d')"
        fi
      shell: bash

    - name: Rebase and force push changes
      run: |
        git fetch origin main
        git rebase origin/main
        git push origin main --force
      shell: bash